blueprint:
  name: Disable entity states
  description: 'Automatically turn off entity if turned on'
  domain: automation
  input:
    entity_1:
      name: First entity
      selector:
        entity:
mode: restart
max_exceeded: silent
trigger:
  - platform: state
    entity_id: !input 'entity_1'
action:
  - service: homeassistant.turn_off
    data:
      entity_id: !input 'entity_1'
