blueprint:
  name: Sync Two Switches
  description: >
    Synchronizes the on/off state between two switch entities.
    If one changes to 'on' or 'off', the other follows.
    Ignores 'unavailable' or 'unknown' states.
  domain: automation
  input:
    switch_1:
      name: Switch 1
      selector:
        entity:
          domain: switch
    switch_2:
      name: Switch 2
      selector:
        entity:
          domain: switch

mode: parallel

trigger:
  - platform: state
    entity_id: !input switch_1
  - platform: state
    entity_id: !input switch_2

condition: []

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state in ['on', 'off'] }}"
        sequence:
          - service: "homeassistant.turn_{{ trigger.to_state.state }}"
            data:
              entity_id: >
                {% set switch_1 = (switch_1 or 'switch.undefined') %}
                {% set switch_2 = (switch_2 or 'switch.undefined') %}
                {% if trigger.entity_id == switch_1 %}
                  {{ switch_2 }}
                {% else %}
                  {{ switch_1 }}
                {% endif %}
