blueprint:
  name: Sync Two Lights
  description: >
    Synchronizes the on/off state between two light entities.
    If one changes state to 'on' or 'off', the other one follows.
    Ignores 'unavailable' or 'unknown' states.
  domain: automation
  input:
    light_1:
      name: Light 1
      selector:
        entity:
          domain: light
    light_2:
      name: Light 2
      selector:
        entity:
          domain: light

mode: parallel

trigger:
  - platform: state
    entity_id: !input light_1
  - platform: state
    entity_id: !input light_2

condition: []

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state in ['on', 'off'] }}"
        sequence:
          - service: "homeassistant.turn_{{ trigger.to_state.state }}"
            data:
              entity_id: >
                {% if trigger.entity_id == light_1 %}
                  {{ light_2 }}
                {% else %}
                  {{ light_1 }}
                {% endif %}
