blueprint:
  name: Sync Two Entities
  description: >
    Synchronizes the on/off state between two entities.
    If one changes to 'on' or 'off', the other follows.
    Ignores 'unavailable' or 'unknown' states.
  domain: automation
  input:
    entity_1:
      name: Entity 1
      selector:
        entity:
    entity_2:
      name: Entity 2
      selector:
        entity:

mode: parallel

trigger:
  - platform: state
    entity_id: !input entity_1
  - platform: state
    entity_id: !input entity_2

condition:
  - condition: template
    value_template: '{{ states(entity_1) != states(entity_2) }}'

action:
  - service: "homeassistant.turn_{{ trigger.to_state.state }}"
    data:
      entity_id: >
        {% if trigger.from_state.entity_id == entity_1 %}
          {{ entity_2 }}
        {% else %}
          {{ entity_1 }}
        {% endif %}
