blueprint:
  name: ZHA - Tuya 4-Button Dimmer Switch
  description: Automate your Tuya 4-Button Dimmer using ZHA events.
  domain: automation
  input:
    tuya_4button_dimmer_switch:
      name: Tuya 4-Button Dimmer Switch
      description: Tuya 4-Button Dimmer Switch to use (TS0044)
      selector:
        device:
          multiple: false
          filter:
            - integration: zha
              manufacturer: _TZ3000_xabckq1v
              model: TS004F
    button_short_press_one:
      name: Short Press 1
      description: Action to run on button upper-left short press
      default: []
      selector:
        action: {}
    button_short_press_two:
      name: Short Press 2
      description: Action to run on button upper-right short press
      default: []
      selector:
        action: {}
    button_short_press_three:
      name: Short Press 3
      description: Action to run on button lower-left short press
      default: []
      selector:
        action: {}
    button_short_press_four:
      name: Short Press 4
      description: Action to run on button lower-right short press
      default: []
      selector:
        action: {}
    button_long_press_one:
      name: Long Press 1
      description: Action to run on button upper-left long press
      default: []
      selector:
        action: {}
    button_long_press_two:
      name: Long Press 2
      description: Action to run on button upper-right long press
      default: []
      selector:
        action: {}
    button_long_press_three:
      name: Long Press 3
      description: Action to run on button lower-left long press
      default: []
      selector:
        action: {}
    button_long_press_four:
      name: Long Press 4
      description: Action to run on button lower-right long press
      default: []
      selector:
        action: {}
    button_double_press_one:
      name: Double Press 1
      description: Action to run on button upper-left double press
      default: []
      selector:
        action: {}
    button_double_press_two:
      name: Double Press 2
      description: Action to run on button upper-right double press
      default: []
      selector:
        action: {}
    button_double_press_three:
      name: Double Press 3
      description: Action to run on button lower-left double press
      default: []
      selector:
        action: {}
    button_double_press_four:
      name: Double Press 4
      description: Action to run on button lower-right double press
      default: []
      selector:
        action: {}
  source_url: https://github.com/radekl/homeassistant/blob/master/tuya-4switch-ts0044.yaml
mode: restart
max_exceeded: silent
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input tuya_4button_dimmer_switch
action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      button_id: "{{ trigger.event.data.endpoint_id }}"
      args: "{{ trigger.event.data.args }}"
  - choose:
    - conditions: "{{ command == 'remote_button_short_press' and button_id == 1 }}"
      sequence: !input button_short_press_one
    - conditions: "{{ command == 'remote_button_short_press' and button_id == 2 }}"
      sequence: !input button_short_press_two
    - conditions: "{{ command == 'remote_button_short_press' and button_id == 3 }}"
      sequence: !input button_short_press_three
    - conditions: "{{ command == 'remote_button_short_press' and button_id == 4 }}"
      sequence: !input button_short_press_four
    - conditions: "{{ command == 'remote_button_long_press' and button_id == 1}}"
      sequence: !input button_long_press_one
    - conditions: "{{ command == 'remote_button_long_press' and button_id == 2}}"
      sequence: !input button_long_press_two
    - conditions: "{{ command == 'remote_button_long_press' and button_id == 3}}"
      sequence: !input button_long_press_three
    - conditions: "{{ command == 'remote_button_long_press' and button_id == 4}}"
      sequence: !input button_long_press_four
    - conditions: "{{ command == 'remote_button_double_press' and button_id == 1}}"
      sequence: !input button_double_press_one
    - conditions: "{{ command == 'remote_button_double_press' and button_id == 2}}"
      sequence: !input button_double_press_two
    - conditions: "{{ command == 'remote_button_double_press' and button_id == 3}}"
      sequence: !input button_double_press_three
    - conditions: "{{ command == 'remote_button_double_press' and button_id == 4}}"
      sequence: !input button_double_press_four
